gh label create "domain:admin" --color "FF6B6B" --description "Related to admin domain functionality"
gh label create "domain:analytics" --color "4ECDC4" --description "Related to analytics domain functionality"
gh label create "domain:auth" --color "45B7D1" --description "Related to authentication domain functionality"
gh label create "domain:compliance" --color "96CEB4" --description "Related to compliance domain functionality"
gh label create "domain:dashboard" --color "FFEAA7" --description "Related to dashboard domain functionality"
gh label create "domain:dispatch" --color "DDA0DD" --description "Related to dispatch domain functionality"
gh label create "domain:ifta" --color "98D8C8" --description "Related to IFTA domain functionality"
gh label create "domain:onboarding" --color "F7DC6F" --description "Related to onboarding domain functionality"
gh label create "domain:settings" --color "BB8FCE" --description "Related to settings domain functionality"
gh label create "domain:vehicles" --color "85C1E9" --description "Related to vehicles domain functionality"
gh label create "phase:survey" --color "0052CC" --description "Survey phase - identifying and cataloging files"
gh label create "phase:planning" --color "0747A6" --description "Planning phase - creating refactoring strategy"
gh label create "phase:execution" --color "36B37E" --description "Execution phase - implementing changes"
gh label create "phase:documentation" --color "FFAB00" --description "Documentation phase - updating docs"
gh label create "phase:validation" --color "6554C0" --description "Validation phase - testing and verification"
gh label create "task:cleanup" --color "FF5630" --description "Removing unused code/files"
gh label create "task:dedup" --color "FF8B00" --description "Deduplicating code and logic"
gh label create "task:separation" --color "00B8D9" --description "Separating client/server components"
gh label create "task:organization" --color "00875A" --description "Organizing files and folders"
gh label create "task:optimization" --color "6554C0" --description "Optimizing actions/fetchers/types"
gh label create "task:auth" --color "8777D9" --description "Auth/RBAC/permissions related"
gh label create "task:database" --color "5243AA" --description "Database/Prisma schema related"
gh label create "priority:critical" --color "D93F0B" --description "Critical priority - blocks other work"
gh label create "priority:high" --color "FF8B00" --description "High priority - important for domain completion"
gh label create "priority:medium" --color "FFAB00" --description "Medium priority - standard workflow"
gh label create "priority:low" --color "36B37E" --description "Low priority - nice to have"
gh label create "status:awaiting-approval" --color "FFAB00" --description "Waiting for user approval to proceed"
gh label create "status:in-progress" --color "0052CC" --description "Currently being worked on"
gh label create "status:review-needed" --color "6554C0" --description "Ready for review"
gh label create "status:blocked" --color "FF5630" --description "Blocked by dependencies or issues"

echo "✅ All audit workflow labels created successfully!"